### ISSUE TITLE
Link to bonus lessons not working.

### ISSUE THREAD

**Issue by brenna** [ladieslearningcode/llc-intro-to-jquery#5]
On the wrap up slide there is a link to bonus lessons that's not working. Looks like the`framework/bonus-flexslider.html` file is no longer available. 

Should that file be added back in or the link removed? I can PR with the link removed if it's no longer part of the workshop.

**Comment by christinatruong** [comment]
Yes that link should have been removed.  If you can update that would be great! Thanks.

**Comment by brenna** [comment]
Thanks, updated my PR ( #6 ) with the fix.
